version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: local-mysql-concert
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: concert
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./libs/persistence/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data:
  redis_data:
  kafka_data:  # Kafka 데이터 저장소 추가 가능
    driver: local
